"""
processor.py — Update Package Processor
Azure Static Web App companion script.

Usage:
    python processor.py --zip <local_zip_path> --container-path <azure_blob_path>

Dependencies:
    pip install azure-storage-blob

Example:
    python processor.py \
        --zip "C:/Temp/downloads/ASUS/BIOS/asus_bios_v310.zip" \
        --container-path "drivers/ASUS/BIOS/asus_bios_v310.zip" \
        --connection-string "DefaultEndpointsProtocol=https;AccountName=..."
"""

import argparse
import json
import os
import re
import shutil
import sys
import tempfile
import zipfile
from pathlib import Path
from datetime import datetime, timezone

# ── Azure SDK (optional at import time; validated at runtime) ─────────────────
try:
    from azure.storage.blob import BlobServiceClient
    AZURE_AVAILABLE = True
except ImportError:
    AZURE_AVAILABLE = False

# ─────────────────────────────────────────────────────────────────────────────
# DETECTION TABLES
# ─────────────────────────────────────────────────────────────────────────────

OEM_PATTERNS = {
    "ASUS":    [r"\basus\b", r"\basustek\b"],
    "HP":      [r"\bhp\b", r"\bhewlett.?packard\b", r"\bompaq\b"],
    "Lenovo":  [r"\blenovo\b", r"\bthinkpad\b", r"\bideapad\b"],
    "Dell":    [r"\bdell\b", r"\blatitude\b", r"\binspiron\b", r"\bxps\b"],
    "AMD":     [r"\bamd\b", r"\bradeon\b", r"\bryzen\b"],
    "Generic": [],
}

COMPONENT_PATTERNS = {
    "BIOS":    [r"\bbios\b", r"\buefi\b", r"\bfirmware\b", r"\bflash\b"],
    "GFX":     [r"\bgfx\b", r"\bgraphics\b", r"\bgpu\b", r"\bradeon\b", r"\bdisplay\b", r"\bvideo\b"],
    "Chipset": [r"\bchipset\b", r"\bamd.?b\d{3}\b", r"\bamd.?x\d{3}\b"],
    "NPU":     [r"\bnpu\b", r"\bneural\b", r"\bai\b", r"\bxdna\b"],
    "WLAN":    [r"\bwlan\b", r"\bwifi\b", r"\bwireless\b", r"\bwi.fi\b", r"\b802\.11\b"],
}

# Maps a detected installer type to the install.bat template to use
INSTALL_BAT_TEMPLATES = {
    "winflash": (
        "@echo off\r\n"
        ":: Auto-generated by processor.py — WinFlash BIOS updater\r\n"
        "cd /d \"%~dp0\"\r\n"
        "set FLASHER={installer_file}\r\n"
        "if not exist \"%FLASHER%\" (\r\n"
        "    echo ERROR: Flash utility not found: %FLASHER%\r\n"
        "    exit /b 1\r\n"
        ")\r\n"
        "echo Running BIOS flash: %FLASHER%\r\n"
        "\"%FLASHER%\" /silent /nobackup\r\n"
        "exit /b %ERRORLEVEL%\r\n"
    ),
    "inf": (
        "@echo off\r\n"
        ":: Auto-generated by processor.py — INF driver installer\r\n"
        "cd /d \"%~dp0\"\r\n"
        "set INF_FILE={installer_file}\r\n"
        "if not exist \"%INF_FILE%\" (\r\n"
        "    echo ERROR: INF file not found: %INF_FILE%\r\n"
        "    exit /b 1\r\n"
        ")\r\n"
        "echo Staging driver: %INF_FILE%\r\n"
        "pnputil /add-driver \"%INF_FILE%\" /install\r\n"
        "exit /b %ERRORLEVEL%\r\n"
    ),
    "exe": (
        "@echo off\r\n"
        ":: Auto-generated by processor.py — EXE silent installer\r\n"
        "cd /d \"%~dp0\"\r\n"
        "set INSTALLER={installer_file}\r\n"
        "if not exist \"%INSTALLER%\" (\r\n"
        "    echo ERROR: Installer not found: %INSTALLER%\r\n"
        "    exit /b 1\r\n"
        ")\r\n"
        "echo Running installer: %INSTALLER%\r\n"
        "\"%INSTALLER%\" /s /v\"/qn\"\r\n"
        "exit /b %ERRORLEVEL%\r\n"
    ),
    "msi": (
        "@echo off\r\n"
        ":: Auto-generated by processor.py — MSI silent installer\r\n"
        "cd /d \"%~dp0\"\r\n"
        "set MSI_FILE={installer_file}\r\n"
        "if not exist \"%MSI_FILE%\" (\r\n"
        "    echo ERROR: MSI package not found: %MSI_FILE%\r\n"
        "    exit /b 1\r\n"
        ")\r\n"
        "echo Installing MSI: %MSI_FILE%\r\n"
        "msiexec /i \"%MSI_FILE%\" /qn /norestart\r\n"
        "exit /b %ERRORLEVEL%\r\n"
    ),
    "unknown": (
        "@echo off\r\n"
        ":: Auto-generated by processor.py — Unknown installer type\r\n"
        ":: TODO: Replace the line below with the correct install command\r\n"
        "cd /d \"%~dp0\"\r\n"
        "echo WARNING: Installer type could not be determined automatically.\r\n"
        "echo Please review the extracted files and update this script.\r\n"
        "dir /b\r\n"
        "exit /b 1\r\n"
    ),
}

# ─────────────────────────────────────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────────────────────────────────────

def _match_patterns(text: str, pattern_map: dict) -> str:
    """Return the first key whose patterns match text (case-insensitive)."""
    text_lower = text.lower()
    for label, patterns in pattern_map.items():
        for pat in patterns:
            if re.search(pat, text_lower):
                return label
    return list(pattern_map.keys())[-1]  # fallback = last key (Generic / WLAN)


def detect_oem(name: str) -> str:
    return _match_patterns(name, OEM_PATTERNS)


def detect_component(name: str) -> str:
    for label, patterns in COMPONENT_PATTERNS.items():
        for pat in patterns:
            if re.search(pat, name, re.IGNORECASE):
                return label
    return "Unknown"


def walk_files(root: str) -> list[Path]:
    """Return all files under root, recursively."""
    return [p for p in Path(root).rglob("*") if p.is_file()]


def rel(path: Path, base: str) -> str:
    return str(path.relative_to(base))


# ─────────────────────────────────────────────────────────────────────────────
# CORE ANALYSIS
# ─────────────────────────────────────────────────────────────────────────────

def analyse_package(extract_dir: str, zip_name: str) -> dict:
    """
    Walk the extracted directory and return a rich analysis dict.

    Returns
    -------
    {
        "oem": str,
        "component": str,
        "install_type": str,           # winflash | inf | exe | msi | unknown
        "installer_file": str,         # relative path inside the archive
        "install_bat_present": bool,
        "install_bat_path": str | None,
        "all_files": [str, ...],
        "inf_files": [str, ...],
        "exe_files": [str, ...],
        "bat_files": [str, ...],
        "msi_files": [str, ...],
    }
    """
    all_files = walk_files(extract_dir)
    rel_files = [rel(f, extract_dir) for f in all_files]

    names_lower = [f.lower() for f in rel_files]

    inf_files  = [f for f in rel_files if f.lower().endswith(".inf")]
    exe_files  = [f for f in rel_files if f.lower().endswith(".exe")]
    bat_files  = [f for f in rel_files if f.lower().endswith(".bat")]
    msi_files  = [f for f in rel_files if f.lower().endswith(".msi")]

    # OEM / component: check filename first, then scan file tree
    combined_name = " ".join([zip_name] + rel_files[:40])  # avoid huge strings
    oem       = detect_oem(combined_name)
    component = detect_component(combined_name)

    # install.bat presence
    install_bat_path = next(
        (f for f in rel_files if os.path.basename(f).lower() == "install.bat"),
        None
    )
    install_bat_present = install_bat_path is not None

    # Determine InstallType + InstallerFile ---------------------------------
    install_type    = "unknown"
    installer_file  = None

    # WinFlash: any exe matching winflash / afulnx / afudos / flashit
    winflash_names = ["winflash", "afulnx", "afudos", "flashit", "wflash", "bflash"]
    for ef in exe_files:
        bn = os.path.basename(ef).lower()
        if any(wf in bn for wf in winflash_names):
            install_type   = "winflash"
            installer_file = ef
            break

    # INF: component-specific, prefer chipset / wlan INFs
    if install_type == "unknown" and inf_files:
        # Prefer an INF named after the component
        pref = next((i for i in inf_files if component.lower() in i.lower()), inf_files[0])
        install_type   = "inf"
        installer_file = pref

    # MSI
    if install_type == "unknown" and msi_files:
        install_type   = "msi"
        installer_file = msi_files[0]

    # EXE: prefer setup.exe, then installer.exe, then first found
    if install_type == "unknown" and exe_files:
        pref_names = ["setup.exe", "installer.exe", "install.exe", "update.exe"]
        pref = next(
            (e for pn in pref_names for e in exe_files if os.path.basename(e).lower() == pn),
            exe_files[0]
        )
        install_type   = "exe"
        installer_file = pref

    # If install.bat exists, it is authoritative as installer_file
    if install_bat_present and install_bat_path:
        installer_file = install_bat_path

    return {
        "oem":                  oem,
        "component":            component,
        "install_type":         install_type,
        "installer_file":       installer_file or "",
        "install_bat_present":  install_bat_present,
        "install_bat_path":     install_bat_path,
        "all_files":            rel_files,
        "inf_files":            inf_files,
        "exe_files":            exe_files,
        "bat_files":            bat_files,
        "msi_files":            msi_files,
    }


# ─────────────────────────────────────────────────────────────────────────────
# INSTALL.BAT GENERATION
# ─────────────────────────────────────────────────────────────────────────────

def generate_install_bat(extract_dir: str, analysis: dict) -> str:
    """
    Write install.bat into extract_dir root.
    Returns the relative path of the generated file.
    """
    install_type   = analysis["install_type"]
    installer_file = os.path.basename(analysis["installer_file"]) if analysis["installer_file"] else ""

    template = INSTALL_BAT_TEMPLATES.get(install_type, INSTALL_BAT_TEMPLATES["unknown"])
    content  = template.format(installer_file=installer_file)

    bat_path = os.path.join(extract_dir, "install.bat")
    with open(bat_path, "w", newline="") as fh:
        fh.write(content)

    print(f"  [+] Generated install.bat ({install_type} template) → {bat_path}")
    return "install.bat"


# ─────────────────────────────────────────────────────────────────────────────
# REZIP
# ─────────────────────────────────────────────────────────────────────────────

def rezip(extract_dir: str, output_zip_path: str) -> None:
    """Create a new ZIP from the entire extract_dir."""
    with zipfile.ZipFile(output_zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for file_path in walk_files(extract_dir):
            arcname = rel(file_path, extract_dir)
            zf.write(file_path, arcname)
    print(f"  [+] Rezipped → {output_zip_path}")


# ─────────────────────────────────────────────────────────────────────────────
# JSON BUILDERS
# ─────────────────────────────────────────────────────────────────────────────

def build_metadirs(container_path: str) -> dict:
    """
    Extract directory components from the blob container path.

    container_path example:
        drivers/ASUS/BIOS/asus_bios_v310.zip
    """
    parts = Path(container_path.replace("\\", "/")).parts  # normalise
    # Strip the filename (last part)
    dir_parts = list(parts[:-1])
    filename   = parts[-1] if parts else ""

    meta = {
        "container_path":  container_path,
        "filename":        filename,
        "dir_segments":    dir_parts,
    }

    # Assign named slots for known depth conventions:
    # e.g.  [root_folder, oem_folder, component_folder, ...]
    labels = ["root_folder", "oem_folder", "component_folder",
              "sub_folder_1", "sub_folder_2", "sub_folder_3"]
    for idx, seg in enumerate(dir_parts):
        key = labels[idx] if idx < len(labels) else f"dir_level_{idx}"
        meta[key] = seg

    meta["generated_at"] = datetime.now(timezone.utc).isoformat()
    return meta


def build_zipmanifest(
    zip_name: str,
    container_path: str,
    analysis: dict,
    bat_generated: bool,
    out_zip_name: str,
) -> dict:
    return {
        "source_zip":          zip_name,
        "container_path":      container_path,
        "output_zip":          out_zip_name,
        "oem":                 analysis["oem"],
        "component":           analysis["component"],
        "install_type":        analysis["install_type"],
        "installer_file":      analysis["installer_file"],
        "install_bat_present": analysis["install_bat_present"],
        "install_bat_generated": bat_generated,
        "file_count":          len(analysis["all_files"]),
        "inf_files":           analysis["inf_files"],
        "exe_files":           analysis["exe_files"],
        "bat_files":           analysis["bat_files"],
        "msi_files":           analysis["msi_files"],
        "all_files":           analysis["all_files"],
        "generated_at":        datetime.now(timezone.utc).isoformat(),
    }


# ─────────────────────────────────────────────────────────────────────────────
# AZURE UPLOAD
# ─────────────────────────────────────────────────────────────────────────────

def upload_to_azure(connection_string: str, container_name: str,
                    blob_prefix: str, local_files: list[tuple[str, str]]) -> None:
    """
    Upload a list of (local_path, blob_name) tuples to Azure Blob Storage.

    blob_name will be placed under  blob_prefix/out/<blob_name>
    """
    if not AZURE_AVAILABLE:
        print("  [!] azure-storage-blob not installed. Skipping upload.")
        print("      Run: pip install azure-storage-blob")
        return

    service_client  = BlobServiceClient.from_connection_string(connection_string)
    container_client = service_client.get_container_client(container_name)

    for local_path, blob_name in local_files:
        dest = f"{blob_prefix}/out/{blob_name}".lstrip("/")
        print(f"  [↑] Uploading {local_path} → {container_name}/{dest}")
        with open(local_path, "rb") as data:
            container_client.upload_blob(name=dest, data=data, overwrite=True)

    print("  [✓] Azure upload complete.")


# ─────────────────────────────────────────────────────────────────────────────
# MAIN PIPELINE
# ─────────────────────────────────────────────────────────────────────────────

def process(
    zip_path: str,
    container_path: str,
    connection_string: str | None = None,
    azure_container_name: str = "$web",
    work_dir: str | None = None,
) -> dict:
    """
    Full pipeline:
      1. Extract ZIP to temp folder
      2. Detect OEM, component, install type, installer file
      3. Generate install.bat if missing
      4. Rezip with install.bat included
      5. Build metadirs.json and zipmanifest.json
      6. Upload new ZIP + JSONs to Azure blob  <container_path>/out/
      7. Return summary dict
    """

    zip_path       = os.path.abspath(zip_path)
    zip_name       = os.path.basename(zip_path)
    base_name      = os.path.splitext(zip_name)[0]
    out_zip_name   = f"{base_name}_processed.zip"

    # Work directory
    if work_dir is None:
        work_dir = tempfile.mkdtemp(prefix="updpkg_")
    extract_dir = os.path.join(work_dir, "extracted")
    out_dir     = os.path.join(work_dir, "output")
    os.makedirs(extract_dir, exist_ok=True)
    os.makedirs(out_dir,     exist_ok=True)

    print(f"\n[1] Extracting {zip_name} → {extract_dir}")
    with zipfile.ZipFile(zip_path, "r") as zf:
        zf.extractall(extract_dir)

    print("[2] Analysing package contents...")
    analysis = analyse_package(extract_dir, zip_name)
    print(f"    OEM:       {analysis['oem']}")
    print(f"    Component: {analysis['component']}")
    print(f"    InstallType: {analysis['install_type']}")
    print(f"    InstallerFile: {analysis['installer_file']}")
    print(f"    install.bat present: {analysis['install_bat_present']}")

    bat_generated = False
    if not analysis["install_bat_present"]:
        print("[3] install.bat not found — generating...")
        new_bat = generate_install_bat(extract_dir, analysis)
        analysis["install_bat_path"]    = new_bat
        analysis["install_bat_present"] = True
        bat_generated = True
    else:
        print(f"[3] install.bat already present at {analysis['install_bat_path']}")

    print("[4] Rezipping...")
    out_zip_path = os.path.join(out_dir, out_zip_name)
    rezip(extract_dir, out_zip_path)

    print("[5] Building JSON metadata...")
    metadirs    = build_metadirs(container_path)
    zipmanifest = build_zipmanifest(
        zip_name, container_path, analysis, bat_generated, out_zip_name
    )

    metadirs_path    = os.path.join(out_dir, "metadirs.json")
    zipmanifest_path = os.path.join(out_dir, "zipmanifest.json")

    with open(metadirs_path,    "w") as f:
        json.dump(metadirs,    f, indent=2)
    with open(zipmanifest_path, "w") as f:
        json.dump(zipmanifest, f, indent=2)

    print(f"    metadirs.json    → {metadirs_path}")
    print(f"    zipmanifest.json → {zipmanifest_path}")

    # Derive the blob folder prefix (everything except the filename)
    blob_prefix = "/".join(container_path.replace("\\", "/").split("/")[:-1])

    if connection_string:
        print("[6] Uploading to Azure Blob Storage...")
        upload_to_azure(
            connection_string,
            azure_container_name,
            blob_prefix,
            [
                (out_zip_path,     out_zip_name),
                (metadirs_path,    "metadirs.json"),
                (zipmanifest_path, "zipmanifest.json"),
            ],
        )
    else:
        print("[6] No Azure connection string provided — skipping upload.")
        print(f"    Output files are in: {out_dir}")

    print("\n[✓] Pipeline complete.\n")

    return {
        "work_dir":         work_dir,
        "out_dir":          out_dir,
        "out_zip":          out_zip_path,
        "metadirs_path":    metadirs_path,
        "zipmanifest_path": zipmanifest_path,
        "analysis":         analysis,
        "metadirs":         metadirs,
        "zipmanifest":      zipmanifest,
    }


# ─────────────────────────────────────────────────────────────────────────────
# CLI ENTRY POINT
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Process an OEM update ZIP package for fleet deployment."
    )
    parser.add_argument("--zip",              required=True,  help="Path to the source ZIP file")
    parser.add_argument("--container-path",   required=True,  help="Azure blob path the ZIP was loaded from (e.g. drivers/ASUS/BIOS/file.zip)")
    parser.add_argument("--connection-string",default=None,   help="Azure Storage connection string")
    parser.add_argument("--container-name",   default="$web", help="Azure blob container name (default: $web)")
    parser.add_argument("--work-dir",         default=None,   help="Local work directory (default: system temp)")

    args = parser.parse_args()

    result = process(
        zip_path=args.zip,
        container_path=args.container_path,
        connection_string=args.connection_string,
        azure_container_name=args.container_name,
        work_dir=args.work_dir,
    )

    # Print a quick summary
    zm = result["zipmanifest"]
    print("─" * 60)
    print(f"  OEM:           {zm['oem']}")
    print(f"  Component:     {zm['component']}")
    print(f"  Install type:  {zm['install_type']}")
    print(f"  Installer:     {zm['installer_file']}")
    print(f"  .bat generated:{zm['install_bat_generated']}")
    print(f"  Output ZIP:    {result['out_zip']}")
    print("─" * 60)